version: '3'

services:
    'selenium':
        image: selenium/standalone-chrome:3.141.59-xenon
        volumes: 
            - "/dev/shm:/dev/shm"
    
    'sanriovote':
        build: .
        depends_on: 
            - 'selenium'
